---
title: "Copepod Crosses/Mating"
author: "Manali Rege-Colt"
date: "2023-07-05"
output: 
  md_document:
    variant: markdown_github
---
# Copepod Crosses

This protocol can be used to determine if different populations/clades are reproductively isolated due to mitonuclear incompatibilities. It is a work in progress and open to edits!

1. Collect 12 clean glass vials (purchased for urchin         larvae).

2. Fill each vial with 10 mL of FSW and 250 ugC/L of algae.    Be sure to ethanol pipettes before and after use!

3. Separate 12 late stage female copepodites from general     culture and ensure there are no spermataphores attached    to individuals. These need to be virgin females. 

4. Once the females have been triple checked and confirmed    to be C4/5 copepodites, distribute them into the           prepared vials. 

5. After 24 hours, check individuals under a scope for age,    health and survival. 

6. Check every 24 hours until individuals have reached        adulthood. 

          *perform water changes every 48 hours*

7. Once females have reached adulthood, add an adult male     to each vial. 

8. Allow individuals to mate for 72 hours without a water     change, checking every 24 hours for eggs. If               fecundity or hatching success rate is variable of          importance, transfer adults to a new vial.

9. If studying hatching success rate, check vials every 24    hours for nauplii

The whole experiment will take ~1 week